export const ADDTOCART = 'ADD_TO_CART';
export const REMOVEFROMCART = 'REMOVE_FROM_CART';
export const RESETCART = 'RESET_CART';
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST';